version: '3.8'

services:
  frontend:
    build: .
    container_name: puttana_frontend
    ports:
      - '${Font_Port}:5173'
    networks:
      - puttana
    environment:
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=1000
    volumes:
      - .:/app  # Bind mount the current directory to /app in the container
      - /app/node_modules  # Use a volume for node_modules to avoid syncing issues

volumes:
  db_puttana:

networks:
  puttana:
