version: '3.8'

services:
  db:
    image: postgres
    container_name: puttana_db
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: puttana_db
      POSTGRES_USER: user
    ports:
      - '1111:5432'
    volumes:
      - db_puttana:/var/lib/postgresql/data
    networks:
      - puttana

  backend:
    build: ./backend
    container_name: puttana_backend
    ports:
      - '2222:2222'
    environment:
      DB_HOST: db
      DB_USER: user
      DB_PASSWORD: 1234
      DB_NAME: puttana_db
    depends_on:
      - db
    networks:
      - puttana

  frontend:
    build: .
    container_name: puttana_frontend
    ports:
      - '3333:5173'
    depends_on:
      - backend
    networks:
      - puttana

volumes:
  db_puttana:
networks:
  puttana:
