version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: puttana_db
    ports:
      - ":${POSTGRES_PORT}:5432"  # Changed to use default PostgreSQL port
    volumes:
      - db_puttana:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - puttana

  backend:
    build: ./BackendPT
    container_name: puttana_backend
    ports:
      - '${port}:${port}'
    environment:
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
    depends_on:
      - postgres
    networks:
      - puttana

  frontend:
    build: .
    container_name: puttana_frontend
    ports:
      - '${Font_Port}:5173'
    depends_on:
      - backend
    networks:
      - puttana
    environment:
     - CHOKIDAR_USEPOLLING=true

volumes:
  db_puttana:

networks:
  puttana:
