version: "3.8"

name: Puttana
services:
  postgres:
    image: postgres:16-alpine
    container_name: puttana_db
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - db_puttana:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - puttana

  backend:
    build: ./BackendPT
    container_name: puttana_backend
    ports:
      - "${BackendPORT}:3000"
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - postgres
    networks:
      - puttana
    env_file:
      - ./.env
    volumes:
      - ./BackendPT:/app
      - /app/node_modules

  # frontend:
  #   container_name: puttana_frontend
  #   build:
  #     context: .  
  #     dockerfile: Dockerfile
  #   ports:
  #     - "${FrontendPORT}:5173"
  #   networks:
  #     - puttana
  #   depends_on:
  #     - backend
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
  #     - VITE_HOST=0.0.0.0
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules

volumes:
  db_puttana:

networks:
  puttana:
