version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: puttana_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: puttana
    ports:
      - "6666:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
